### PR TITLE
add ServiceConfigURLDelegate for protostuff

### PR DESCRIPTION
**Pull request by zrlw**
## What is the purpose of the change
* add protostuff serialization
* fix ServiceConfigURL of dubbo 3.0  serialization problem: public parameters such as application,version are not be transferred

### CODE REVIEW

**Comment by zrlw** [comment]
@xiaoheng1

**Comment by songxiaosheng** [comment]
please fix  conficts, thanks

**Comment by zrlw** [comment]
> please fix conficts, thanks

fixed. I'm surprised that this PR committed two years ago is still existed.

**Comment by songxiaosheng** [comment]
> > please fix conficts, thanks
> 
> fixed. I'm surprised that this PR committed two years ago is still existed.
thanks，we can try  merge it

**Review by AlbumenJ — APPROVED** [review]

**Comment by zrlw** [comment]
re-enable test_URL_mutable_withType  at  AbstractSerializationTest.java since it could be also used by KryoPersonOkTest and KyroSerializationTest.

**Review by songxiaosheng — APPROVED** [review]
LGTM

**Pull request merged**
