### PR TITLE
add dubbo-serialization-kryo5 kryo 5.X extend

### PR DESCRIPTION
**Pull request by JavaLionLi**
## What is the purpose of the change

支持kryo 5.X版本 5.X解决了一些4.X的安全漏洞 性能也有所提升 维护也很活跃 4.X已经很久不维护了 最后提交时间是2018年

## Brief changelog

复制了一份4.X版本的插件 做了5.X的适配 
参考4.X的单测全部通过
image

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before
  you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address
  just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit
  in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency
  exist. If the new feature or significant change is committed, please remember to add sample
  in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure
  unit-test and integration-test pass.
- [ ] If this contribution is large, please follow
  the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by JavaLionLi** [comment]
https://github.com/apache/dubbo/issues/10687

**Comment by JavaLionLi** [comment]
考虑兼容老插件 故直接修改了pom依赖版本 防止依赖冲突
如果不考虑兼容的话 也可以提交一个直接在原插件更改的pr

**Comment by EarthChen** [comment]
fix it & ut

**Comment by JavaLionLi** [comment]
> fix it & ut

image
这个问题跟我无关的吧

**Comment by JavaLionLi** [comment]
> fix it & ut

https://github.com/apache/dubbo-spi-extensions/pull/142
Resubmitted a version and upgraded it in the original plug-in

**Comment by AlbumenJ** [comment]
重新 merge 下master分支

**Comment by JavaLionLi** [comment]
> image
> 
> Please fix ut

本地跑没有问题的啊
image

**Comment by AlbumenJ** [comment]
> > image
> > Please fix ut
> 
> 本地跑没有问题的啊 image

看一下依赖传递的问题，可能是版本号不一样了导致的。
本地可以使用 mvn clean test 测试

**Comment by JavaLionLi** [comment]
> > > image
> > > Please fix ut
> > 
> > 
> > 本地跑没有问题的啊 image
> 
> 看一下依赖传递的问题，可能是版本号不一样了导致的。 本地可以使用 mvn clean test 测试

看一下另一个pr吧 https://github.com/apache/dubbo-spi-extensions/pull/142
这个打算关闭了

**Comment by JavaLionLi** [comment]
> > > image
> > > Please fix ut
> > 
> > 
> > 本地跑没有问题的啊 image
> 
> 看一下依赖传递的问题，可能是版本号不一样了导致的。 本地可以使用 mvn clean test 测试

两个依赖相互覆盖 搞不了

**Pull request closed without merging**
