### PR TITLE
feature: support kryo 5.3.0

### PR DESCRIPTION
**Pull request by JavaLionLi**
## What is the purpose of the change

支持kryo 5.X版本 5.X解决了一些4.X的安全漏洞 性能也有所提升 维护也很活跃 4.X已经很久不维护了 最后提交时间是2018年

## Brief changelog

对原有插件做了5.X的适配
单测全部通过
image

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before
  you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address
  just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit
  in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency
  exist. If the new feature or significant change is committed, please remember to add sample
  in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure
  unit-test and integration-test pass.
- [ ] If this contribution is large, please follow
  the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by JavaLionLi** [comment]
test_LoopReference StackOverflowError 目前没有找到解决方案

**Comment by JavaLionLi** [comment]
> test_LoopReference StackOverflowError 目前没有找到解决方案

正在尝试和kryo社区的人沟通
https://github.com/EsotericSoftware/kryo/issues/919

**Comment by AlbumenJ** [comment]
> test_LoopReference StackOverflowError 目前没有找到解决方案

有明确原因吗

**Comment by JavaLionLi** [comment]
> > test_LoopReference StackOverflowError 目前没有找到解决方案
> 
> 有明确原因吗

目前无法确定 对kryo了解的还不够深

**Comment by JavaLionLi** [comment]
> > test_LoopReference StackOverflowError 目前没有找到解决方案
> 
> 有明确原因吗

经过跟社区沟通 references 从 5.X 开始被默认位 false
已经提交相关修复

**Comment by AlbumenJ** [comment]
image

**Comment by JavaLionLi** [comment]
> image

image
这个模块加载的是远程maven的组件 并不是我本地的 这块要如何修改他

**Comment by JavaLionLi** [comment]
> image

image
image
这块的依赖被 dubbo-bom 覆盖了 要如何修改它呢

**Comment by AlbumenJ** [comment]
> > image
> 
> image image 这块的依赖被 dubbo-bom 覆盖了 要如何修改它呢

这个依赖看下能不能替换成 dubbo-extensions-dependencies-bom 里面的

**Comment by JavaLionLi** [comment]
> > > image
> > 
> > 
> > image image 这块的依赖被 dubbo-bom 覆盖了 要如何修改它呢
> 
> 这个依赖看下能不能替换成 dubbo-extensions-dependencies-bom 里面的

已经覆盖了

**Review by AlbumenJ — APPROVED** [review]

**Pull request merged**
